"""Registers the ``bbopen://`` URL protocol under the current user.

Run once per machine::

    python install.py

Writes only under ``HKEY_CURRENT_USER\\Software`` - no admin rights needed,
and nothing outside the current user's own registry hive is touched.
``python install.py --remove`` deletes it again (and the compiled exe).

The registered command is a small compiled ``bb_launch.exe`` next to this
script, not ``pythonw.exe`` directly - confirmed the hard way against a real
Chrome install: ``start bbopen://...`` from a terminal (ShellExecute) ran
pythonw.exe fine, while the identical URL navigated to from a page failed
with "the scheme does not have a registered handler." Chromium silently
refuses external-protocol handoff to well-known shared script interpreters
(python.exe/pythonw.exe, cmd.exe, powershell.exe, wscript.exe, ...) as
hardening against protocol-handler command injection, regardless of how the
registry itself is set up - a registration pointing at Discord's own
Discord.exe, structurally identical to this one otherwise, works fine.

bb_launch.exe is therefore a thin, generated shim, rebuilt by this script via
PyInstaller: it does nothing but hand its one argument to ``pythonw.exe
bb_launch.py``. The actual resolution and launch logic still lives in, and
runs live from, bb_launch.py - editing that file takes effect immediately,
with no rebuild - only the shim's own existence is compiled, because it is
the shim's identity as a dedicated exe (not what it does) that Chrome checks.

Two registrations are written for the exe, not one. The plain
``Software\\Classes\\bbopen`` key is what ShellExecute (``start
bbopen://...``, the Windows Run dialog) reads. Chrome and Edge also check
the OS's own "Default Programs" mechanism (``RegisteredApplications`` + a
``Capabilities`` block) before handing off a page-triggered navigation.
"""
import subprocess
import sys
import tempfile
import textwrap
import winreg
from pathlib import Path

APP_NAME = "BB Kitsu Launcher"
CLASS_KEY = r"Software\Classes\bbopen"
CAPS_KEY = r"Software\%s\Capabilities" % APP_NAME
REGISTERED_APPS_KEY = r"Software\RegisteredApplications"

HERE = Path(__file__).resolve().parent
EXE_PATH = HERE / "bb_launch.exe"


def _pythonw():
    exe = Path(sys.executable)
    windowless = exe.with_name("pythonw.exe")
    return str(windowless if windowless.is_file() else exe)


def _build_exe():
    """Compile bb_launch.exe: a shim that forwards its argv to bb_launch.py.

    Built fresh on every install rather than committed, since the pythonw.exe
    path and the script path it bakes in are both specific to this machine's
    Python install and this checkout's location.
    """
    script = HERE / "bb_launch.py"
    wrapper_source = textwrap.dedent('''\
        """Generated by install.py - do not edit; re-run install.py instead.

        Exists only so the OS sees a dedicated exe to register the protocol
        against. All real logic lives in bb_launch.py, read live off disk.
        """
        import subprocess
        import sys

        PYTHONW = %r
        SCRIPT = %r

        if __name__ == "__main__":
            subprocess.Popen([PYTHONW, SCRIPT] + sys.argv[1:])
    ''' % (_pythonw(), str(script)))

    with tempfile.TemporaryDirectory(prefix="bb_launch_build_") as build_dir:
        build_dir = Path(build_dir)
        wrapper_path = build_dir / "bb_launch_wrapper.py"
        wrapper_path.write_text(wrapper_source, encoding="utf-8")

        result = subprocess.run(
            [sys.executable, "-m", "PyInstaller",
             "--onefile", "--noconsole", "--name", "bb_launch",
             "--distpath", str(HERE),
             "--workpath", str(build_dir / "build"),
             "--specpath", str(build_dir),
             str(wrapper_path)],
            capture_output=True, text=True)
        if result.returncode != 0:
            raise RuntimeError(
                "building bb_launch.exe failed:\n%s" % (result.stdout + result.stderr))


def install():
    _build_exe()
    command = '"%s" "%%1"' % EXE_PATH

    # The protocol handler itself - what ShellExecute (and Windows' own
    # Run dialog) resolves directly.
    with winreg.CreateKey(winreg.HKEY_CURRENT_USER, CLASS_KEY) as key:
        winreg.SetValueEx(key, "", 0, winreg.REG_SZ, "URL:BB Kitsu launcher")
        winreg.SetValueEx(key, "URL Protocol", 0, winreg.REG_SZ, "")

    with winreg.CreateKey(winreg.HKEY_CURRENT_USER, CLASS_KEY + r"\shell\open\command") as key:
        winreg.SetValueEx(key, "", 0, winreg.REG_SZ, command)
        winreg.SetValueEx(key, "FriendlyAppName", 0, winreg.REG_SZ, APP_NAME)

    # The Default Programs registration Chrome/Edge check before handing a
    # page-triggered navigation off to the OS. bbopen is reused as its own
    # ProgID here since it already carries a shell\open\command.
    with winreg.CreateKey(winreg.HKEY_CURRENT_USER, CAPS_KEY) as key:
        winreg.SetValueEx(key, "ApplicationName", 0, winreg.REG_SZ, APP_NAME)
        winreg.SetValueEx(
            key, "ApplicationDescription", 0, winreg.REG_SZ,
            "Opens a Kitsu task's work file in its DCC")

    with winreg.CreateKey(winreg.HKEY_CURRENT_USER, CAPS_KEY + r"\URLAssociations") as key:
        winreg.SetValueEx(key, "bbopen", 0, winreg.REG_SZ, "bbopen")

    with winreg.CreateKey(winreg.HKEY_CURRENT_USER, REGISTERED_APPS_KEY) as key:
        winreg.SetValueEx(key, APP_NAME, 0, winreg.REG_SZ, CAPS_KEY)

    print("built", EXE_PATH)
    print("registered bbopen:// ->", command)
    print("test with: start bbopen://open?task_id=<a real task id>")
    print("Chrome/Edge may need a restart to pick up the new registration.")


def remove():
    import contextlib

    with contextlib.suppress(FileNotFoundError):
        with winreg.OpenKey(winreg.HKEY_CURRENT_USER, REGISTERED_APPS_KEY,
                            0, winreg.KEY_SET_VALUE) as key:
            winreg.DeleteValue(key, APP_NAME)

    for sub in (r"\URLAssociations", ""):
        with contextlib.suppress(FileNotFoundError):
            winreg.DeleteKey(winreg.HKEY_CURRENT_USER, CAPS_KEY + sub)
    with contextlib.suppress(FileNotFoundError):
        winreg.DeleteKey(winreg.HKEY_CURRENT_USER, r"Software\%s" % APP_NAME)

    for sub in (r"\shell\open\command", r"\shell\open", r"\shell", ""):
        with contextlib.suppress(FileNotFoundError):
            winreg.DeleteKey(winreg.HKEY_CURRENT_USER, CLASS_KEY + sub)

    with contextlib.suppress(FileNotFoundError):
        EXE_PATH.unlink()

    print("removed bbopen:// registration")


if __name__ == "__main__":
    remove() if "--remove" in sys.argv else install()
